version: '3.9'

services:
  backend:
    build:
      context: ./server
      dockerfile: ./dockerfile
    image: "server"
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: ./dockerfile
    image: "frontend"
    ports:
      -  "3000:3000"
    links:
      - "backend"